### ISSUE TITLE
deprecated Zend\ComponentInstaller\ComponentInstaller::onPostPackageInstall

### ISSUE THREAD

**Issue by samsonasik** [zendframework/zend-component-installer#35] opened 2017-02-21 12:33 UTC
PHP: 7.1.1
zend-component-installer version: 0.6.0:

```
Deprecation Notice: The callback Zend\ComponentInstaller\ComponentInstaller::onPostPackageInstall 
declared at /www/zfproject/vendor/zendframework/zend-component-installer/src/ComponentInstaller.php 
accepts a Composer\Script\PackageEvent but post-package-install
 events use a Composer\Installer\PackageEvent instance. 
Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in 
phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:317
```

**Comment by michalbundyra** [comment] 2017-02-21 13:14
@samsonasik can you check please if definitely you are using zend-component-installer in version __0.6.0__?
These deprecation notices were fixed with 0.5.1 release in https://github.com/zendframework/zend-component-installer/pull/29. Please see also current version (0.6.0):
https://github.com/zendframework/zend-component-installer/blob/0.6.0/src/ComponentInstaller.php#L11

**Comment by samsonasik** [comment] 2017-02-21 21:42
yes:
```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 1 update, 0 removals
  - Updating zendframework/zend-component-installer (0.3.1 => 0.6.0) Loading from cache
Deprecation Notice: The callback Zend\ComponentInstaller\ComponentInstaller::onPostPackageInstall declared at /Users/samsonasik/www/zfproject/vendor/zendframework/zend-component-installer/src/ComponentInstaller.php accepts a Composer\Script\PackageEvent but post-package-install events use a Composer\Installer\PackageEvent instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:317
```

**Comment by michalbundyra** [comment] 2017-02-21 21:50
@samsonasik So is it still wrong or is fine now? Sorry, I'm lost ;-) In code all seems to be fine. Thanks!

**Comment by samsonasik** [comment] 2017-02-21 22:35
@webimpress deprecation still shown.

**Comment by weierophinney** [comment] 2017-02-22 17:52
I cannot recreate this currently.

To test, I did the following:

```bash
$ composer create-project zendframework/skeleton-application test
```

This *did* demonstrate the deprecation notices, but that was to be expected; the skeleton is currently pinned to the 0.3.0 release of this package.

I chose to do a minimal install. Interestingly, while the plugin was installed, it was not represented in my `composer.json`; in fact, no `require-dev` section was listed, which was kind of strange. As such, I ran the following:

```bash
$ composer require --dev zendframework/zend-component-installer
```

This installed 0.7.0, which we just tagged today. That release contains no changes to what version of the composer plugin API we require or exercise.

I then did the following:

```bash
$ composer require zendframework/zend-form
```

I received no deprecation notices.

Since we cannot determine how to reproduce, I'm closing the issue.

**Closed as completed by weierophinney** 2017-02-22 17:52 UTC
